### ISSUE TITLE
Issue Number 1

### ISSUE THREAD

**Issue by pascalfiv** [ntoombs19/LA-Enhancer#1]
"Mixed Content: The page at 'https://de118.die-staemme.de/game.php?village=n15304&screen=am_farm&Farm_page=0' was loaded over HTTPS, but requested an insecure script 'http://de118.die-staemme.de/game.php?village=14532&order=distance&dirasc&Farm_page=0&screen=am_farm&_=1440519923840'. This request has been blocked; the content must be served over HTTPS."

Dont know why this is coming or if there is any effect on the script, the only thing I can say your script doesn't work on my computer. Firefox and Chrome both aren't working... 

Script will load normaly but even if i click on any button script won't send any troops, sometimes the script wont load at all. Or an other case is that even if i didn't checked any filter options and click "apply", it hides all farmrows away...
Use Win10 
latest chrome and firefox.

**Comment by ntoombs19** [comment]
This has been fixed

**Comment by pascalfiv** [comment]
thanks now all works great ;)
